plugins {
    id "java-library"
    id "jacoco"
    id 'com.gradleup.shadow' version '9.4.1'
}

repositories {
    mavenCentral()
}

ext {
    sonarApiVersion = '13.5.0.4319'
    sonarqubeVersion = '26.1.0.118079'
}

dependencies {
    compileOnly "org.sonarsource.api.plugin:sonar-plugin-api:${sonarApiVersion}"
    testImplementation "org.sonarsource.api.plugin:sonar-plugin-api:${sonarApiVersion}"
    testImplementation "org.sonarsource.sonarqube:sonar-plugin-api-impl:${sonarqubeVersion}"
    testImplementation "org.sonarsource.api.plugin:sonar-plugin-api-test-fixtures:13.4.3.4290"
    implementation 'org.apache.commons:commons-compress:1.28.0'
    implementation 'com.esotericsoftware.yamlbeans:yamlbeans:1.17'
    implementation 'com.fasterxml.staxmate:staxmate:2.4.1'
    implementation 'commons-io:commons-io:2.21.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    implementation project(':perl-frontend')
    implementation "org.apache.commons:commons-lang3:3.20.0"
}

compileJava {
    options.release = 21
}

jacoco {
    toolVersion = '0.8.14'
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}

test {
    finalizedBy jacocoTestReport
}

jar {
    manifest {
        attributes "Build-Jdk": System.getProperty('java.version'),
                   "Build-Time": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                   "Plugin-BuildDate": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                   'Plugin-Key': 'communityperl',
                   'Plugin-Name': 'Community Perl',
                   'Plugin-Version': project.version,
                   'Implementation-Build': getCheckedOutGitCommitHash(),
                   'Plugin-Class': 'com.github.sonarperl.PerlPlugin',
                   "Plugin-Description": 'Code Analyzer for Perl',
                   "Plugin-Developers": 'Oliver Trosien',
                   "Plugin-Homepage": 'https://github.com/sonar-perl/sonar-perl',
                   "Plugin-IssueTrackerUrl": 'https://github.com/sonar-perl/sonar-perl/issues',
                   "Plugin-License": 'Apache',
                   "Plugin-Organization": 'sonar-perl',
                   "Plugin-OrganizationUrl": 'https://github.com/sonar-perl/',
                   "Plugin-SourcesUrl": 'https://github.com/sonar-perl/sonar-perl',
                   "Plugin-TermsConditionsUrl": 'https://github.com/sonar-perl/sonar-perl',
                   "Sonar-Version": project.ext.sonarApiVersion
    }
}

def getCheckedOutGitCommitHash() {
    'git rev-parse --verify --short HEAD'.execute().text.trim()
}

build.dependsOn shadowJar