FROM sonarqube:5.4

ADD http://downloads.sonarsource.com/plugins/org/codehaus/sonar-plugins/sonar-clover-plugin/3.0/sonar-clover-plugin-3.0.jar /opt/sonarqube/extensions/plugins/sonar-clover-plugin-3.0.jar
COPY build/libs/sonar-perl-plugin.jar /opt/sonarqube/extensions/plugins/sonar-perl-plugin.jar
