all:
	perl gen-perlcritic-rules.pl > ../sonar-perl-plugin/src/main/resources/com/github/sonarperl/perlcritic-rules.xml
	perl gen-sonar-way-profile.pl > ../sonar-perl-plugin/src/main/resources/com/github/sonarperl/sonar-way-profile.xml
	perl gen-perlcritic-cost.pl > ../sonar-perl-plugin/src/main/resources/com/github/sonarperl/cost.csv
